### ISSUE TITLE
The parameters of Ta, Ka are from the calibraion tool IMU-TK

### ISSUE THREAD

**Issue by JourneyGo** [zdxiao/IMU_Calib#1]
Great to be here and nice to meet you, shon!

**Comment by zdxiao** [comment]
Thank you, my dear friend.

**Comment by rim0621** [comment]
hi, i am trying to calibrate my IMU. i saw your code and i have a question.
what is Ta, Ka, Tg, Kg ??? where (or how) can i find proper parameters??
thank you. have a good day~

**Comment by zdxiao** [comment]
Please refer to [imu_tk] (https://bitbucket.org/alberto_pretto/imu_tk/overview) for detail.  I using the calibration tool imu_tk to get those parameters.
